version: '3.5'
services:

  app:
    build: .
    image: foga/django_queue
    restart: "no"
    container_name: django_queue
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: &envfile
      - env.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - broker      

  appfogar:
    build: .
    image: foga/mock
    restart: "no"
    container_name: django_fogar_mock
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    env_file: *envfile
    ports:
      - "8090:8080"
    volumes:
      - ./app_fogar:/app    

  worker:
    build: .
    image: fogar/worker
    restart: "no"
    env_file: *envfile
    command: ["celery", "worker", "--app=worker.worker.app", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO"]
    volumes:
      - ./app:/app
    depends_on:
      - broker
        
  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    restart: "no"
    env_file: *envfile
    ports:
      - "5555:5555"
    depends_on:
      - broker
    
  broker:
    image: rabbitmq:3
    volumes:
      - ./rabbit/data:/var/lib/rabbitmq/mnesia
    env_file: *envfile
    #TODO: para acceder a mas opciones en flower, se requiere activar: rabbitmq-plugins enable rabbitmq_management
    #command: ["rabbitmq-plugins enable rabbitmq_management"] -> no funciona desde acá
    ports:
      - 5672:5672